#index:
#    path: /
#    controller: App\Controller\DefaultController::inde

accueil:
    path: /accueil
    controller: App\Controller\DemoController::accueil


damier:
    path: /damier
    controller: App\Controller\DemoController::damier


addMessage:
    path: /addMessage
    controller: App\Controller\DemoController::addMessage